services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Maispace\MaiTeam\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Maispace\MaiTeam\Controller\TeamMemberController:
    public: true

  Maispace\MaiTeam\Controller\Backend\TeamMemberBackendController:
    public: true
